### ISSUE TITLE
update docs branch readme.md to represent the project

### ISSUE THREAD

**Issue by jacebenson** [jacebenson/atf#180]
update docs branch readme.md to represent the project

**Comment by globefire** [comment]
Hey, @jacebenson Can I update this?

**Comment by jacebenson** [comment]
Sure, It should reflect something to the effect of what https://atf.jace.pro is about.

**Comment by jacebenson** [comment]
Should just be copy/paste from here: https://github.com/jacebenson/atf/blob/791c9ad79163e14304f04cd4751d2314a4dd8123/README.md

**Comment by garg3133** [comment]
@jacebenson Can I work on this as @globefire is not responding?

**Comment by jacebenson** [comment]
sure.
