### ISSUE TITLE
Built Tests for CSM

### ISSUE THREAD

**Issue by jacebenson** [jacebenson/atf#23]
To get started.  

1. Spin up an instance on developer.servicenow.com (london version).
2. Comment on this issue that you want to take it.
3. Fork this project
4. Import your forked project within studio in servicenow
5. Create changes per this issue
6. Commit your app to your fork
7. From your fork, make a Pull request

The desired output is a set of tests to test the functionality of the tool in a out of box state.

[Docs](https://docs.servicenow.com/bundle/london-customer-service-management/page/product/customer-service-management/concept/customer-service-bus-unit-overview.html)

**Comment by jacebenson** [comment]
So CSM comes with some OOB tests of their own;
[Quick Start Tests](https://docs.servicenow.com/bundle/london-application-development/page/administer/auto-test-framework/reference/quick-start-sample-tests.html#quick-start-application-sample-tests)
The problem with these tests is they are not self contained, and rely on other records being generated. 
You could copy these tests but just as part of the test create the records they require.

**Comment by SxMShaDoW** [comment]
@jacebenson - so I am not part of the "hacktoberfest" but I just went HAM on creating ATFs for my company around CSM (probably more than this scope needed).
* Created both UI tests and API tests
* Validated case with portal
* Validated Module / Application Menus
* Validated Accounts, Contact, Interaction, Case forms across multiple views (including CSM workspace) with mandatory,visible, etc fields.
* Validated UI actions
* Validated Email triggers
* Validated metrics (if you create them) around solutions rejected.

Created custom test steps:
* Retrieve a random record (not required for this)
* Add a timeout (just re-used your code). Necessary for email testing

Some quirks that I found that are a pain:
* Creating contact users (but have a solution for this)..

Would you like me to take this issue? I would like to eventually do a Knowledge talk on this stuff as well. Maybe we can collaborate (if you like public speaking)? Won't start for a few weeks, but def can bang this out.

**Comment by SxMShaDoW** [comment]
Also: Is it okay if I do this for New York instead of London? Mostly want to use the "Create user" functionality.

**Comment by SxMShaDoW** [comment]
I could also just re-create the OOB ones if you prefer that (so that they don't rely on demo data)

**Comment by jacebenson** [comment]
Using NY is fine.  Yes. feel free to re-create the OOB ones so they dont rely on demo data.  Feel free to reach out to me and I'll try to be responsive

**Comment by jacebenson** [comment]
I've set you to the assigned to.  Let me know if I can do anything to help.

**Comment by jacebenson** [comment]
Thanks for the reminder.  closing as tests are made.
